import Head from "next/head";
import AccomodationDetail from "../../components/accomodation";


export default function Accomodation() {
	return (
		<div>
			<Head>
				<title>RentBuyParis</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<AccomodationDetail />
			</main>
		</div>
	);
}
