import Head from "next/head";
import { useRouter } from "next/router";

// Lib
import { loadAccomodations } from "../lib/loadAccomodations";

// Components
import AccomodationsHub from "../components/accomodationsHub";

// Animation
import { motion } from "framer-motion";
import { pageAnimation } from "../lib/animation";

const Accomodations = ({ accomodations }) => {
	const router = useRouter();
	const property = router.query.property;

	const filteredAccomodations = accomodations.data.filter((d) =>
		property == "buy"
			? d.attributes.isRent == false
			: d.attributes.isRent == true
	);

	return (
		<div>
			<Head>
				<title>RentBuyParis</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<motion.main
				variants={pageAnimation}
				initial='hidden'
				animate='show'
				exit='exit'>
				<AccomodationsHub accomodations={filteredAccomodations} />
			</motion.main>
		</div>
	);
};

export async function getStaticProps() {
	const accomodations = await loadAccomodations();
	return { props: { accomodations }, revalidate: 3 };
}

export default Accomodations;
