import Head from "next/head";
import Hero from "../components/hero";
import SectionText from "../components/sectionText";
import styled from "styled-components";
import { bgColorPrimary, bgColorSecondary } from "../styles/colors.module.scss";
import SectionAvailableNow from "../components/sectionAvailableNow";
export default function Home() {
	return (
		<div>
			<Head>
				<title>RentBuyParis | Locations et ventes d'appartements à Paris</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<HeroWrapper>
				<Hero />
			</HeroWrapper>
			<SectionAvailableNow />

			<SectionText />
		</div>
	);
}

const HeroWrapper = styled.div`
	@media screen and (min-width: 768px) {
		background-color: ${bgColorPrimary};
		padding: 0rem 2rem 0rem 2rem;
	}

	@media screen and (min-width: 1024px) {
		background-color: ${bgColorPrimary};
		padding: 0rem 2rem 0rem 2rem;

	}
	@media screen and (min-width: 1440px) {
		background-color: ${bgColorPrimary};
		padding: 0rem 12rem 0rem 12rem;

	}
	@media screen and (min-width: 2550px) {
		background-color: ${bgColorPrimary};
		padding: 0rem 25rem 0rem 25rem;

	}
`;

